// Generated by scripts/sync-credits.mjs — do not edit by hand.
export const credits = JSON.parse('{"mediaTranslationPerMin":60,"lipSyncPerMin":90,"ttsPer200Chars":2,"cloneVoicePerVoice":10,"textTranslationPer100Chars":1}');
