#!/usr/bin/env node
/**
 * Sync Open API credit rates into snippets/credits.jsx from the same public endpoint
 * vmeg-web-mono reads (t_operation_credits_config).
 *
 * Usage: node scripts/sync-credits.mjs [--check]
 *   --check  exit 1 if snippets/credits.jsx is out of date (no write)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "snippets/credits.jsx");
const url = "https://www.vmeg.ai/api/operation/credits/get-all?currentPage=1&pageSize=1&dataGeneration=v3.0";

// Defaults mirror vmeg-serv pro.vmeg.openapi.*QuotaService when the key is absent from config.
const KEYS = {
  mediaTranslationPerMin: ["translation-proofread-per-cost"],
  lipSyncPerMin: ["lip-syc-per-cost"],
  ttsPer200Chars: ["voiceover-proofread-200-cost"],
  cloneVoicePerVoice: ["openapi-clone-voice-cost", 10],
  textTranslationPer100Chars: ["openapi-translate-cost", 1],
};

const res = await fetch(url);
const body = await res.json();
const cfg = body?.data?.data;
if (!res.ok || body.code !== 0 || !cfg) throw new Error(`Bad response from ${url}: ${res.status} ${JSON.stringify(body).slice(0, 200)}`);

const credits = {};
for (const [name, [key, fallback]] of Object.entries(KEYS)) {
  const v = cfg[key] != null ? Number(cfg[key]) : fallback;
  if (!Number.isFinite(v)) throw new Error(`Missing or invalid credit key "${key}"`);
  credits[name] = v;
}
// Docs show one media translation rate for vt and at.
if (Number(cfg["audio-translation-proofread-per-cost"]) !== credits.mediaTranslationPerMin) {
  throw new Error("Video and audio translation rates differ; update guides/pricing.mdx to show both.");
}

const content = `// Generated by scripts/sync-credits.mjs — do not edit by hand.
export const credits = JSON.parse('${JSON.stringify(credits)}');
`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (current !== content) {
    console.error(`snippets/credits.jsx is out of date. Run: node scripts/sync-credits.mjs\n${JSON.stringify(credits)}`);
    process.exit(1);
  }
  console.log("snippets/credits.jsx is up to date");
} else {
  fs.writeFileSync(out, content);
  console.log(`Wrote snippets/credits.jsx ${JSON.stringify(credits)}`);
}
